language: node_js
node_js:
  - node
# cache:
#   directories:
#     - node_modules
install:
  - npm i
script:
  - npm run build:ui-doc
  - npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: docs/.vuepress/dist
  on:
    branch: master