language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn build:ui-doc
  - yarn docs:build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local-dir: docs/.vuepress/dist
  on:
    branch: master